### ISSUE TITLE
ESP32-Wroom Dev. board

### ISSUE THREAD

**Issue by MrSejlund** [ehorvat1/NES-MEP-Reader#2]
Could this project be done single handed by a ESP32-Wroom dev. board?
https://www.aliexpress.com/item/1005003818288234.html?

**Comment by glynge** [comment]
Hi MrSejlund
I'm not directly involved in this GitHub, but is running a similar one here: [https://github.com/dabblerdk](https://github.com/dabblerdk) and is also helping maintaining the OSGP GitHub where the interface specifications is published ([https://github.com/OSGP-Alliance-MEP-and-Optical](https://github.com/OSGP-Alliance-MEP-and-Optical))

As the Echelon/NES smart meter is using RS232 and the ESP32 is using 3.3v TTL logic on the serial interface, you'll need something to convert these levels. It can be done with resistors (as voltage dividers) and transistors - but it would be easier to use a MAX3232 IC or similar (i.e. something like this if you prefer a PCB: [https://www.ebay.com/itm/314217971261](https://www.ebay.com/itm/314217971261)).

Best Regards
Gert Lynge
gert@dabbler.dk

**Comment by ehorvat1** [comment]
Hi MrSejlund,
in fact I did my first tests with a ESP32 Wroom board which you have mentioned. But as Gert already mentioned, in any case you need some means of converting the RS232 signal levels to a ESP32 compatible (quasi TTL) level. For this reason a RS3232 chip is used.
Kind Regards,
Engelbert

**Comment by ehorvat1** [comment]
Closed
