### ISSUE TITLE
MEP indicator red forever in the webinterface

### ISSUE THREAD

**Issue by HanspeterH** [ehorvat1/NES-MEP-Reader#5]
Hi
If for some reason the readout of MEP data fails, the MEP indicator in the web interface turns red and also the text "MEP: No data from Smartmeter for the last 30 seconds" appears in the header part of the webinterface and stays there forever (probably until a restart of the ESP happens), although data is readout perfectly as can be seen in the webinterface.

**Comment by ehorvat1** [comment]
Grüetzi Hanspeter, thank you for the input. 
I hope you are running on latest FW Update (which is not in releases but only in the main repository) . I implemented changes regarding Table BT23 about 5 days ago to the repo. But this is not related to the issue you bring up here.
I will check this ... Rg, Bert

**Comment by HanspeterH** [comment]
Thanks for looking at the problem. After the esp reboot everything is green again...
Rg. Hanspeter

**Comment by ehorvat1** [comment]
Hi Hanspeter, 
I think I have fixed this now. 
In file: AmsToMqttBridge.cpp the line 1545 must not be commented out since it clears the MEP error... it must execute: meterState.setLastError(DATA_PARSE_OK);
On my setup this was ok, but please test it yourself. File firmware.bin is including this changes now also. To have the correct version date shown in ESP Informations page you probably have to clear the Browser cache. Rg, Bert

**Comment by HanspeterH** [comment]
if I provide power over USB, the result is the same. I will install the original firmware, which was working so far...and see what happens...

**Comment by ehorvat1** [comment]
Strange....I have used the firmware file on my site and then uploaded it to Github. For sure it is better to first test with USB supply...you can also download (even) older firmware.bin files from the releases.

**Comment by HanspeterH** [comment]
I think I have a HW problem of the serial connection..will resolder cable connections...

**Comment by HanspeterH** [comment]
telnet debug looks strange to me...
Serving /minuteplot.json over http...
(I) Buffer length actual of minuteplot.json...is: 1251,
(I) Buffer length actual of minuteplot.json...is: 1251,
(D) Serving /data.json over http...
(I) (loop)(C1) ++++++  EHo +++ Stations connected to AP: 0
(I) Serving /minuteplot.json over http...
(I) Buffer length actual of minuteplot.json...is: 676,
(I) Buffer length actual of minuteplot.json...is: 1251,
(D) Serving /data.json over http...
(I) (loop)(C1) RS3232 reset 2/2. Dropping buffer with this contents:
(I) (loop)(C1) Giving up on reqest at index 1073519684 - too may retries

Any ideas on this?

**Comment by HanspeterH** [comment]
I installed the newest firmware but it displays still the following:
Installierte Version: pre 2.6-ge
Datum: 12 Sept. 2023

**Comment by HanspeterH** [comment]
The ESP indicator problem is probably fixed but I cannot test it because the MEP readout does not work right now for strange, unknown reasons.

**Comment by ehorvat1** [comment]
Just uploaded files for above mentioned updates...

**Comment by HanspeterH** [comment]
Hi Bert
Thanks for the additional information and the additional fix.I still have to figure out, why my serial connection stopped working...

**Comment by HanspeterH** [comment]
I think as a consequence of a non working serial mep connection, the SW gets into a loop when debug level info is active over telnet:

(I t:1323065ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323080ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323095ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323110ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323124ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323139ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323153ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323168ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323183ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323198ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323212ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323242ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323258ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323273ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323287ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323302ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323316ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323331ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323345ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323360ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323375ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323390ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323404ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323419ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323434ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323449ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323463ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323478ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323492ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323507ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323522ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323537ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323551ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323566ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323581ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323596ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323610ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323625ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
(I t:1323640ms) (loop)(C1) Giving up on reqest at index 2146435072 - too may retries
 this goes on foever...

**Comment by HanspeterH** [comment]
I have updated to newest firmware...    no more loop so far when no mep connection possible...
Rg. Hanspeter

**Comment by ehorvat1** [comment]
Good, I just wanted to suggest FW update....

**Comment by ehorvat1** [comment]
Hi Hanspeter, may I suggest that you get in contact with the guys from makerspace Reinach? But somehow I have the feeling that you know them already.... anyway, if not check them out on www at https://makerspace-reinach.ch/ 
Rg, Bert

**Comment by HanspeterH** [comment]
Hallo BertDanke für den Hinweis….ich bin Mitglied im Makerspace ReinachLG HanspeterHanspeter - www.funlab.ch - Funlab, Grenzacherweg 307, 4125 Riehen - 079-225 96 49Am 10.12.2023 um 11:14 schrieb ehorvat1 ***@***.***>:﻿
Hi Hanspeter, may I suggest that you get in contact with the guys from makerspace Reinach? But somehow I have the feeling that you know them already.... anyway, if not check them out on www at https://makerspace-reinach.ch/
Rg, Bert

**Comment by ehorvat1** [comment]
Closed the issue since initial error is fixed.
